import {findVersion,readPreferences} from './catalog.mjs';
const KEY='fvt-landing-r1',track=document.getElementById('campaigns'),reduced=matchMedia('(prefers-reduced-motion: reduce)'),mobile=matchMedia('(max-width: 740px)');
let raw=null;try{raw=localStorage.getItem(KEY);}catch{}const prefs=readPreferences(raw);
function save(){try{localStorage.setItem(KEY,JSON.stringify(prefs));}catch{}}
function country(id,scroll=false){prefs.country=id;document.querySelectorAll('[data-country]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.country===id)));document.querySelectorAll('.campaign').forEach(c=>c.dataset.active=String(c.id===id));document.querySelectorAll('[data-dot]').forEach(d=>d.classList.toggle('active',d.dataset.dot===id));if(scroll&&mobile.matches){const card=document.getElementById(id);track.scrollTo({left:card.offsetLeft-track.offsetLeft-16,behavior:reduced.matches?'instant':'smooth'});}save();}
function version(id,announce=false){const v=findVersion(id);if(!v)return;prefs[v.country]=id;const card=document.getElementById(v.country);card.querySelectorAll('[data-version]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.version===id)));document.getElementById(v.country+'-count').textContent=v.missions+' MISIONES';document.getElementById(v.country+'-detail').textContent=v.detail;const play=document.getElementById('play-'+v.country);play.href=v.url;play.dataset.selectedVersion=id;play.querySelector('.play-version').textContent=v.short;play.setAttribute('aria-label','Jugar '+v.label+', '+v.missions+' misiones');if(announce)document.getElementById('announcement').textContent=v.label+' seleccionada. '+v.missions+' misiones.';save();}
function last(){const v=findVersion(prefs.last),box=document.getElementById('last-opened');box.hidden=!v;if(v){document.getElementById('last-label').textContent=v.label;document.getElementById('last-link').href=v.url;}}
document.querySelectorAll('[data-country]').forEach(b=>b.addEventListener('click',()=>country(b.dataset.country,true)));
document.querySelectorAll('[data-version]').forEach(b=>b.addEventListener('click',()=>{version(b.dataset.version,true);country(findVersion(b.dataset.version).country);}));
document.querySelectorAll('.play').forEach(a=>a.addEventListener('click',()=>{prefs.last=a.dataset.selectedVersion;country(findVersion(prefs.last).country);save();last();}));
document.querySelector('.country-switch').addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight'].includes(e.key))return;e.preventDefault();const id=e.key==='ArrowLeft'?'chile':'france';country(id,true);document.querySelector('[data-country='+id+']').focus({preventScroll:true});});
let queued=false;track.addEventListener('scroll',()=>{if(!mobile.matches||queued)return;queued=true;requestAnimationFrame(()=>{queued=false;const center=track.getBoundingClientRect().left+track.clientWidth/2;const closest=[...track.children].sort((a,b)=>Math.abs((a.getBoundingClientRect().left+a.getBoundingClientRect().right)/2-center)-Math.abs((b.getBoundingClientRect().left+b.getBoundingClientRect().right)/2-center))[0];country(closest.id);});},{passive:true});
for(const id of ['chile','france'])version(prefs[id]);country(prefs.country);last();
function align(){if(mobile.matches){const card=document.getElementById(prefs.country);track.scrollTo({left:card.offsetLeft-track.offsetLeft-16,behavior:'instant'});}}
requestAnimationFrame(align);addEventListener('pageshow',align);mobile.addEventListener('change',align);
document.documentElement.dataset.ready='true';
